name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装系统依赖 libtinfo5
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5

      - name: Buildozer编译APK
        uses: digreatbrian/buildozer-action@v2
        env:
          BUILDOZER_ACCEPT_LICENSE: "y"
        with:
          python-version: "3.10"
          buildozer-cmd: buildozer -v android debug

      - name: 上传APK成品
        uses: actions/upload-artifact@v4
        with:
          name: apk成品
          path: ./bin/*.apk
